"use client";

import { FormEvent, useState } from "react";
import type { CloudSyncController } from "../lib/cloud-sync";
import { hasVaultPin } from "../lib/vault-pin";
import VaultPinDialog from "./VaultPinDialog";

export default function CloudSyncCard({sync,onToast}:{sync:CloudSyncController;onToast:(message:string)=>void}){
  const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[pinMode,setPinMode]=useState<"setup"|"verify"|null>(null);
  const label={not_configured:"Setup needed",connecting:"Connecting",signed_out:"Not signed in",syncing:"Syncing",synced:"Protected & synced",offline:"Offline — changes queued",error:"Needs attention"}[sync.status];
  const activePinMode=sync.user&&!hasVaultPin()?"setup":pinMode;
  async function submit(mode:"signin"|"create"){
    setBusy(true);
    try{if(mode==="create")await sync.createAccount(email,password);else await sync.signIn(email,password);setPassword("");onToast(mode==="create"?"Private sync account created":"Signed in — syncing your vault")}
    catch(error){onToast(error instanceof Error?error.message:"Could not sign in")}
    finally{setBusy(false)}
  }
  if(!sync.configured)return <section className="cloud-sync-card needs-setup"><div className="cloud-sync-head"><span className="cloud-glyph">☁</span><div><p>CLOUD VAULT</p><h3>Desktop + mobile sync</h3><span className="cloud-status"><i/>Setup needed</span></div></div><p className="cloud-copy">Add the Firebase web app values from <code>.env.example</code>, rebuild once, then sign in on both devices.</p><div className="cloud-note">Your Firebase private key never belongs in the app. These public web-app values identify the project; Firestore rules protect the vault.</div></section>;
  if(sync.user)return <><section className="cloud-sync-card connected"><div className="cloud-sync-head"><span className="cloud-glyph">✓</span><div><p>PRIVATE CLOUD VAULT</p><h3>{sync.user.email}</h3><span className={`cloud-status ${sync.status}`}><i/>{label}</span></div></div><p className="cloud-copy">Renewals, thoughts, activity, profile and reminder settings sync automatically on every signed-in device. Offline changes are queued safely.</p>{sync.error&&<div className="cloud-error">{sync.error}</div>}<div className="cloud-actions"><button disabled={busy||sync.status==="syncing"} onClick={()=>{setBusy(true);void sync.syncNow().then(()=>onToast("Vault synced now")).catch(()=>onToast("Sync will retry when online")).finally(()=>setBusy(false))}}>↻ Sync now</button><button className="quiet protected-signout" onClick={()=>setPinMode(hasVaultPin()?"verify":"setup")}>Sign out · PIN required</button></div>{sync.lastSyncedAt&&<small className="cloud-last">Last checked {new Date(sync.lastSyncedAt).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"})}</small>}</section>{activePinMode&&<VaultPinDialog key={activePinMode} mode={activePinMode} onCancel={activePinMode==="verify"?()=>setPinMode(null):undefined} onVerified={async()=>{if(activePinMode==="setup"){setPinMode(null);onToast("Private vault PIN secured");return}setBusy(true);try{await sync.signOutAccount();setPinMode(null);onToast("Signed out securely")}finally{setBusy(false)}}}/>}</>;
  return <section className="cloud-sync-card"><div className="cloud-sync-head"><span className="cloud-glyph">☁</span><div><p>PRIVATE CLOUD VAULT</p><h3>Restore or sync your vault</h3><span className={`cloud-status ${sync.status}`}><i/>{label}</span></div></div><p className="cloud-copy">After reinstalling, sign in once with the same email to restore renewals, thoughts, activity, profile and settings from Firestore. Your password is handled by Firebase and is never stored by PicSecure Renew.</p><form className="cloud-auth-form" onSubmit={(event:FormEvent)=>{event.preventDefault();void submit("signin")}}><label><span>Email</span><input type="email" autoComplete="email" required value={email} onChange={event=>setEmail(event.target.value)} placeholder="you@example.com"/></label><label><span>Password</span><input type="password" autoComplete="current-password" required minLength={6} value={password} onChange={event=>setPassword(event.target.value)} placeholder="Minimum 6 characters"/></label>{sync.error&&<div className="cloud-error">{sync.error}</div>}<button className="cloud-primary" disabled={busy}>{busy?"Please wait…":"Sign in & restore"}</button><div className="cloud-actions"><button type="button" disabled={busy||!email||password.length<6} onClick={()=>void submit("create")}>Create private account</button><button type="button" className="quiet" disabled={!email} onClick={()=>{setBusy(true);void sync.resetPassword(email).then(()=>onToast("Password reset email sent")).catch(error=>onToast(error instanceof Error?error.message:"Could not send reset email")).finally(()=>setBusy(false))}}>Forgot password</button></div></form></section>;
}

